[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"

[licenses]
allow = [
  "MIT",
  "MIT-0",
  "Unlicense",
  "ISC",
  "Unicode-DFS-2016",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MPL-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "OpenSSL",
  "CC0-1.0",
]
exceptions = [
  # As stated in https://github.com/gakonst/ethers-rs/blob/master/deny.toml
  # CC0 is a permissive license but somewhat unclear status for source code
  # so we prefer to not have dependencies using it
  # https://tldrlegal.com/license/creative-commons-cc0-1.0-universal
  { allow = ["CC0-1.0"], name = "tiny-keccak" },
]
