[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"

[licenses]
allow = [
  "MIT",
  "Unlicense",
  "ISC",
  "Unicode-DFS-2016",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MPL-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "OpenSSL",
]
exceptions = [
  # As stated in https://github.com/gakonst/ethers-rs/blob/master/deny.toml
  # CC0 is a permissive license but somewhat unclear status for source code
  # so we prefer to not have dependencies using it
  # https://tldrlegal.com/license/creative-commons-cc0-1.0-universal
  { allow = ["CC0-1.0"], name = "tiny-keccak" },
]

[[licenses.clarify]]
name = "ring"
# SPDX considers OpenSSL to encompass both the OpenSSL and SSLeay licenses
# https://spdx.org/licenses/OpenSSL.html
# ISC - Both BoringSSL and ring use this for their new files
# MIT - "Files in third_party/ have their own licenses, as described therein. The MIT
# license, for third_party/fiat, which, unlike other third_party directories, is
# compiled into non-test libraries, is included below."
# OpenSSL - Obviously
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
