[reth]
db = "/mnt/data/eth/sepolia/reth/db"
static_files = "/mnt/data/eth/sepolia/reth/static_files"
rpc_url = "http://localhost:8545"

[chain]
chain_id = 11155111
start_block = 4700000

[sync]
buffer_size = 1000

[http]
port = 8080
jwt_secret_env = "ETHUI_JWT_SECRET"

[db]
url = "postgres://ethui_indexer:ethui-indexer&12345@localhost/ethui_indexer"

[payment]
address = "0x0063A660Fb166E9deF01C7B4fd0303B054Ed1B9e"
min_amount = "10000000000000000"                       # 0.01 ether

[whitelist]
file = "/home/naps62/ethui/whitelists/lists/all.txt"
