[reth]
db = "/mnt/data/eth/sepolia/reth/db"
static_files = "/mnt/data/eth/sepolia/reth/static_files"

[chain]
chain_id = 11155111
start_block = 4700000

[sync]
buffer_size = 1000

[http]
port = 8080

[db]
url = "postgres://iron_indexer:iron-indexer&12345@localhost/iron_indexer"
