CREATE TABLE backfill_jobs (
  id SERIAL NOT NULL,
  addresses BYTEA[] NOT NULL,
  chain_id INTEGER NOT NULL,
  low INTEGER NOT NULL,
  high INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (chain_id) REFERENCES chains (chain_id)
);
