[reth]
db = "/mnt/data/eth/sepolia/reth/db"

[chain]
chain_id = 11155111
start_block = 4700000

[sync]
buffer_size = 10000
backfill_concurrency = 1000

[db]
url = "postgres://ethui_indexer:ethui-indexer&12345@localhost/ethui_indexer_test"
